Adds TLS support for STOMP connections
opensciencegrid/xrootd-monitoring-shoveler pull request #16
Opened 2023-02-01 16:35 UTC by kazeborja

This PR aims to provide TLS support for STOMP connections using certificates.
This is needed as at CERN TLS authentication is handled using certificates.

2023-02-01 18:03 UTC, djw8605 requested changes
The Go standard is to use tabs, not spaces, for indention.  The rest of the files are tab separated.  I believe you can reformat the files with the command:
```
$ go fmt
```

2023-02-01 18:03 UTC, djw8605 commented on config/config.yaml
> +mq: amqp/stomp
You should comment out this line, otherwise it fails testing.
```suggestion
# mq: amqp/stomp
```

2023-02-02 07:49 UTC, kazeborja commented
Thanks Derek for the pointers, I always forget about go fmt tool

2023-02-07 14:22 UTC, djw8605 approved these changes
LGTM

2023-02-07 14:22 UTC, merged